# Generated by Django 3.1.3 on 2023-03-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20230310_0828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
